#!/bin/bash

JSON_FILE="movies.json"
LOG_FILE="movies_spider.log"

if [ -f $LOG_FILE ]; then
	echo "Clearing log file..."
	>$LOG_FILE
fi

if [ -f $JSON_FILE ]; then
    echo "Cleaning old JSON data..."
    rm -f $JSON_FILE
fi

# Crawl
scrapy crawl movie_spider 
